### ISSUE TITLE
MacOS setup constant typo

### ISSUE THREAD

**Issue by peterp415** [apocalyptech/pystarboundmap#1]
There is an undefined constant.  Changing the line at
https://github.com/apocalyptech/pystarboundmap/blob/b10634d60aa9d1ba8c0d6b85210fe6123e0adf36/pystarboundmap/config.py#L47
to read
```
     cur_os = OS_MAC
```
allows this to run on MacOS.  And it picks up the Steam game files perfectly on my system and runs great, thank you!

**Comment by apocalyptech** [comment]
Thanks for the report!  Quite a boneheaded typo, there.  :)  I'll cut a new official release with this fix.  Thanks a bunch!
