### ISSUE TITLE
Materials with comments

### ISSUE THREAD

**Issue by CVex2150J** [apocalyptech/pystarboundmap#2]
Nice work with this starbound world viewer.

I downloaded the python package using pip and when I launched the application, the windows always close after 0.2 sec without any error message.

I choose to clone the project and when I lauched it using pycharm debugger I pin-point the issue. The code crash loading Starbound assets `'/tiles/materials/slopedpolygon.material'` which contains a commented line.

Using 
`material = read_config(pakdata.get(matpath))`
instead of 
`material = json.loads(pakdata.get(matpath))` Line 813
fix it for me

I also change the parsing of **matmodpath** (line 833) just in case

**Comment by apocalyptech** [comment]
Aha, thanks for the info!  I'll take a look at that tomorrow and get it fixed.  I assume it's probably due to some updates that have happened since I last poked at this -- I know there's been at least one majorish release in the meantime.

**Comment by apocalyptech** [comment]
Okay, thanks again!  Agreed that that fix seems to do the trick.  I've committed and also released 1.0.0b7, so if you update via pip you should be good to go.

Have a good one!
