### ISSUE TITLE
The Mod wont install 

### ISSUE THREAD

**Issue by ZeroOneGuy** [apocalyptech/pystarboundmap#3]
Hi creators of mod , for last few weeks i was trying to install the modification and the problem is (i have install all the requirements ) the setup.py not getting pillow and cancel the installation , with this situation i cannot use the mod , please fix the problem and/or show with video or a better tutorial for install. 
PS: Transform the mod in a real installer (the installer make the adjustments ) like a setup.exe.
  
[the error log.txt](https://github.com/apocalyptech/pystarboundmap/files/4542755/the.error.log.txt)

**Comment by apocalyptech** [comment]
Hello!  It looks like the most important bit of the error message is this one:

    Pillow does not yet support Python 3.8 and does not yet provide prebuilt Windows binaries.
    We do not recommend building from source on Windows.

So it looks like for now on Windows, you might want to downgrade to Python 3.7 instead, and that should get things installed a bit more easily.  Let me know if that does the trick for you, and I could get the docs updated with that info!

As for a real installer, I agree that would be nice to have, but I don't have any Windows installations, so I'd be at the mercy of other folks.  If you can get something put together which compiles things together properly in a nice installable package, I might be able to merge that in as a PR and figure out a way to distribute those binaries.

**Comment by ZeroOneGuy** [comment]
Thank you for the reply and apologizes if I  have been rude in the message above (my frustration and anger isn't excuse for act like that) , furthermore again i say thanks.

**Comment by apocalyptech** [comment]
Oh, no worries!  Your post was fine, no offense taken.  :)
